# Sử dụng Node.js LTS nhẹ
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json và package-lock.json
COPY package*.json ./

# Cài đặt dependencies
RUN npm install --production

# Copy toàn bộ source code
COPY . .

# Expose port
EXPOSE 3000

# Chạy server
CMD ["node", "server.js"]